In [14]:
%%capture
!wget https://raw.githubusercontent.com/karpathy/makemore/refs/heads/master/names.txt

In [1]:
import pandas as pd

# Define the embedding data
data = {
    "Word": ["king", "queen", "man", "woman", "apple", "banana", "city", "village", "car", "bus"],
    "Masculine": [0.95, 0.10, 0.98, 0.05, 0.00, 0.00, 0.20, 0.20, 0.30, 0.30],
    "Feminine": [0.05, 0.90, 0.02, 0.95, 0.00, 0.00, 0.20, 0.20, 0.30, 0.30],
    "Royalty": [0.98, 0.97, 0.10, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],
    "Food": [0.00, 0.00, 0.00, 0.00, 0.95, 0.90, 0.00, 0.00, 0.00, 0.00],
    "Sweetness": [0.00, 0.00, 0.00, 0.00, 0.90, 0.85, 0.00, 0.00, 0.00, 0.00],
    "Urban": [0.30, 0.30, 0.40, 0.40, 0.10, 0.10, 0.95, 0.60, 0.60, 0.60],
    "Transport": [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.10, 0.10, 0.95, 0.90],
    "Size": [0.80, 0.75, 0.70, 0.68, 0.20, 0.25, 0.85, 0.40, 0.55, 0.75]
}

# Create the DataFrame
embedding_df = pd.DataFrame(data)

# Display the DataFrame
embedding_df

,Word,Masculine,Feminine,Royalty,Food,Sweetness,Urban,Transport,Size
0,king,0.95,0.05,0.98,0.00,0.00,0.30,0.00,0.80
1,queen,0.10,0.90,0.97,0.00,0.00,0.30,0.00,0.75
2,man,0.98,0.02,0.10,0.00,0.00,0.40,0.00,0.70
3,woman,0.05,0.95,0.10,0.00,0.00,0.40,0.00,0.68
4,apple,0.00,0.00,0.00,0.95,0.90,0.10,0.00,0.20
5,banana,0.00,0.00,0.00,0.90,0.85,0.10,0.00,0.25
6,city,0.20,0.20,0.00,0.00,0.00,0.95,0.10,0.85
7,village,0.20,0.20,0.00,0.00,0.00,0.60,0.10,0.40
8,car,0.30,0.30,0.00,0.00,0.00,0.60,0.95,0.55
9,bus,0.30,0.30,0.00,0.00,0.00,0.60,0.90,0.75


In [6]:
import numpy as np

In [7]:
v1 = embedding_df.iloc[0, 1:].to_numpy()
v2 = embedding_df.iloc[2, 1:].to_numpy()

np.linalg.norm(v1 - v2)

np.float64(0.8923003978481686)

In [8]:
v1 = embedding_df.iloc[0, 1:].to_numpy()
v2 = embedding_df.iloc[5, 1:].to_numpy()

np.linalg.norm(v1 - v2)

np.float64(1.9340113753543438)

In [28]:
import torch
import torch.nn.functional as F

In [11]:
torch.randint(0, 100, (10,))

tensor([30, 84, 64, 75, 33, 49, 73, 78, 91, 45])

In [13]:
m = 8
torch.randn(10, m)

tensor([[-1.0486,  0.6219,  1.4934, -0.3562, -1.1737, -0.8147, -1.4468,  0.7459],
        [ 1.7307,  0.1292, -0.1821, -1.3812,  0.5017,  2.0327,  1.8141, -0.5899],
        [ 1.2398, -0.5631,  0.8308, -1.7598, -0.0867,  0.1464, -0.1416,  0.7607],
        [-0.2121,  0.4605, -1.1570, -0.1434,  0.7186, -0.0617,  0.1476, -0.9768],
        [-0.8018, -0.3044,  1.0592,  0.1290, -0.9523,  0.0248, -1.6211,  1.5819],
        [ 1.4354,  1.3395,  1.0458, -0.5477,  0.8342, -0.0675,  1.2473,  1.5758],
        [-0.2251, -0.5789, -0.4260, -2.5703, -1.0913, -1.1286, -0.7369,  1.2787],
        [-1.0199,  1.6959, -0.0610,  0.1144, -0.6811,  0.8601, -0.5194, -0.7795],
        [-0.3316, -1.0865,  0.9978, -0.6655, -1.8837, -1.2137,  0.0383,  0.5761],
        [-1.5587, -0.7865,  0.5959, -1.1439,  0.7635, -0.7625, -0.3296,  1.2408]])

In [21]:
names = open('names.txt').read().splitlines()
vocab = sorted(set(''.join(names) + '.'))
stoi = {v:k for k, v in enumerate(vocab)}
itos = {v:k for k, v in stoi.items()}

def decode(seq: list[int]) -> str:
    return ''.join([itos[i] for i in seq])

def encode(name: str) -> list[int]:
    return [stoi[s] for s in name]

In [73]:
block_size = 3

X = []
Y = []

for name in names:
    context = [0] * block_size
    for ch in name + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        # print(f"{context} -> {ix}")
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

In [82]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        ...,
        [26, 26, 25],
        [26, 25, 26],
        [25, 26, 24]])

In [106]:
vocab_size = 27
block_size = 3
n_embd = 4
n_hidden = 50

C = torch.randn(vocab_size, n_embd, requires_grad=True)
W1 = torch.randn(block_size * n_embd, n_hidden, requires_grad=True)
b1 = torch.randn(n_hidden, requires_grad=True)
W2 = torch.randn(n_hidden, vocab_size, requires_grad=True)
b2 = torch.randn(vocab_size, requires_grad=True)

W3 = torch.randn(block_size * n_embd, vocab_size, requires_grad=True)

params = [C, W1, b1, W2, b2, W3]

In [107]:
# This entire block must be in a loop
# forward pass
xenc = C[X]
x_emb = xenc.view(xenc.size(0), -1)
h_preact = x_emb @ W1 + b1
h = torch.tanh(h_preact)
logits = h @ W2 + b2 + x_emb @ W3

# loss
loss = F.cross_entropy(logits, Y)

# zero grad

loss.backward()

# update params